baseURL = 'https://www.jonsen.jp/'
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'JOnsen'
 

  # Main Menu
  [[menu.Main]]
  name = "Previous"
  url= "/previous/"
  weight = 1
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 2
  [[menu.Main]]
  name = "CoC"
  url= "/code-of-conduct/"
  weight = 3

  # Sitemap Menu
  # [[menu.sitemap]]
  # name = "Privacy Policy"
  # url = "/privacy/"
  # weight = 1
  # [[menu.sitemap]]
  # name = "Terms"
  # url = "/terms/"
  # weight = 2

[params]
  # theme_overrides = "css/overrides.css"
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} JJUG"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  # googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo.png"
  footerlogo = "images/logo.png"
  # footerDescription = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit quia ab, natus fugiat voluptas saepe ipsum animi officiis in molestiae?"

  # Social icons
    [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/japanjug/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/jjug/"
  weight = 2
  
  
